[package]
name = "troller-rs"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
handlebars = "6.4.0"
nom = "8.0.0"
poise = "0.6.1"
rand = "0.9.2"
resvg = "0.46.0"
rusqlite = "0.38.0"
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
